name: .NET Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-matrix:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [win-x86, win-x64, win-arm64]
        include:
          - rid: win-x86
            zipname: ClassWizard-1.0-amd-x86-package.zip
          - rid: win-x64
            zipname: ClassWizard-1.0-amd64-x64-package.zip
          - rid: win-arm64
            zipname: ClassWizard-1.0-aarch64-arm64-package.zip

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish for ${{ matrix.rid }}
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Zip output
      run: |
        cd bin\Release\net8.0\${{ matrix.rid }}\publish
        powershell Compress-Archive -Path * -DestinationPath ..\..\..\${{ matrix.zipname }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.zipname }}
        path: bin\Release\${{ matrix.zipname }}

  general-net-only:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Publish framework-dependent (net8.0)
      run: dotnet publish -c Release -r win-x64 --self-contained false

    - name: Zip net8.0 package
      run: |
        cd bin\Release\net8.0\win-x64\publish
        powershell Compress-Archive -Path * -DestinationPath ..\..\..\ClassWizard-1.0-net8.0package.zip

    - name: Upload .NET-only artifact
      uses: actions/upload-artifact@v4
      with:
        name: ClassWizard-1.0-net8.0package.zip
        path: bin\Release\ClassWizard-1.0-net8.0package.zip
